# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logCLnormal <- function(beta, cov, block_y, block_x, m, n) {
    .Call('_DIMM_logCLnormal', PACKAGE = 'DIMM', beta, cov, block_y, block_x, m, n)
}

logCLnormal_par <- function(beta, cov, block_y, block_x, m, n) {
    .Call('_DIMM_logCLnormal_par', PACKAGE = 'DIMM', beta, cov, block_y, block_x, m, n)
}

eenormalmean <- function(beta, cov, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalmean', PACKAGE = 'DIMM', beta, cov, block_y, block_x, m, n)
}

eenormalmean_par <- function(beta, cov, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalmean_par', PACKAGE = 'DIMM', beta, cov, block_y, block_x, m, n)
}

eenormalderivmean <- function(cov, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalderivmean', PACKAGE = 'DIMM', cov, block_y, block_x, m, n)
}

eenormalderivmean_par <- function(cov, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalderivmean_par', PACKAGE = 'DIMM', cov, block_y, block_x, m, n)
}

eenormalCSvar <- function(beta, sigma, rho, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalCSvar', PACKAGE = 'DIMM', beta, sigma, rho, block_y, block_x, m, n)
}

eenormalCSvar_par <- function(beta, sigma, rho, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalCSvar_par', PACKAGE = 'DIMM', beta, sigma, rho, block_y, block_x, m, n)
}

eenormalAR1var <- function(beta, sigma, rho, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalAR1var', PACKAGE = 'DIMM', beta, sigma, rho, block_y, block_x, m, n)
}

eenormalAR1var_par <- function(beta, sigma, rho, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalAR1var_par', PACKAGE = 'DIMM', beta, sigma, rho, block_y, block_x, m, n)
}

eenormalindvar <- function(beta, sigma, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalindvar', PACKAGE = 'DIMM', beta, sigma, block_y, block_x, m, n)
}

eenormalindvar_par <- function(beta, sigma, block_y, block_x, m, n) {
    .Call('_DIMM_eenormalindvar_par', PACKAGE = 'DIMM', beta, sigma, block_y, block_x, m, n)
}

